name: Release

on:
  push:
    tags:
      - 'v*.*.*'   # trigger on semver-like tags: v1.2.3

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: write
  id-token: write  # (optional) for npm provenance if you add --provenance

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Verify tag matches package.json version
        id: verify
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          PKG_VERSION=$(node -p "require('./package.json').version")
          NAME=$(node -p "require('./package.json').name")
          echo "Tag: v$TAG"
          echo "Package: $NAME@$PKG_VERSION"

          if [ "$TAG" != "$PKG_VERSION" ]; then
            echo "::error::Git tag (v$TAG) does not match package.json version ($PKG_VERSION)"
            exit 1
          fi

          if [[ "$NAME" == @*/* ]]; then
            echo "scoped=true" >> $GITHUB_OUTPUT
          else
            echo "scoped=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Pack (dry run)
        run: npm pack --dry-run

      - name: Publish to npmjs (public)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        shell: bash
        run: |
          if [ "${{ steps.verify.outputs.scoped }}" = "true" ]; then
            npm publish --access public
          else
            npm publish
          fi

      # Optional: publish to GitHub Packages (only if package name is scoped like @owner/name)
      - name: Publish to GitHub Packages (optional)
        if: secrets.GH_PACKAGES_TOKEN != '' && steps.verify.outputs.scoped == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        shell: bash
        run: |
          npm publish --registry=https://npm.pkg.github.com